version: '3.7'
services:
  node-api:
    build:
      context: ./node-api
      args:
        - PORT=3000
      envvironment:
        - NODE_ENV=test
    ports:
      - '3000:3000'
  next-app:
    build: ./next-app
    ports:
      - '80:3000'
    depends_on:
      - node-api
