import Head from 'next/head';

export default function Home({ message }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Hi there!</h1>
        <p>{message}</p>
      </div>
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch('http://node-api:3000/api');
  const data = await res.json();

  return {
    props: {
      message: data?.message,
    },
  };
}
